version: "3.8"

services:
  nginx:
    image: asanalii/ayirbasta-frontend:latest
    ports:
      - "8081:80"
    networks:
      - app-net
    depends_on:
      - backend
    deploy:
      replicas: 1

  backend:
    image: asanalii/ayirbasta-backend:latest
    environment:
      - MONGO_URI=mongodb+srv://testa:asan1234@test.wr2lcrn.mongodb.net/?retryWrites=true&w=majority&appName=test&tls=true&tlsAllowInvalidCertificates=true
    networks:
      - app-net
    deploy:
      replicas: 1

networks:
  app-net:
    driver: overlay
