version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-net
    deploy:
      replicas: 1

  frontend:
    image: asanalii/ayirbasta-frontend:latest
    networks:
      - app-net
    deploy:
      replicas: 1

  backend:
    image: asanalii/ayirbasta-backend:latest
    environment:
      - MONGO_URI=mongodb+srv://...
    networks:
      - app-net
    deploy:
      replicas: 1

volumes:
  frontend-dist:

networks:
  app-net:
    driver: overlay
