version: "3.8"

services:
  frontend:
    build: ./frontend
    volumes:
      - frontend-dist:/app/build
    networks:
      - app-net

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend-dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-net
    deploy:
      replicas: 1

  backend:
    image: asanalii/ayirbasta-backend:latest
    environment:
      - MONGO_URI=mongodb+srv://testa:asan1234@test.wr2lcrn.mongodb.net/?retryWrites=true&w=majority&appName=test&tls=true&tlsAllowInvalidCertificates=true
    networks:
      - app-net
    deploy:
      replicas: 1

volumes:
  frontend-dist:

networks:
  app-net:
    driver: overlay
